languageCode = "en"
languageName = "English"
weight = 1
title = "Forensic Meta-Science"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "&copy; { year } Ian Hussey"

 [author]
   name = "Ian Hussey"
   image = "profile_ianhussey.jpg"
   headline = "Forensic Meta-Science Resources"
   bio = "Open source tools and methods for checking the consistency and integrity of reported statistical results."
   links = [
     { email = "mailto:ian.hussey@unibe.ch" },
     { github = "https://github.com/ianhussey" },
     { orcid = "https://orcid.org/0000-0001-8906-7559" },
   ]
