# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.

[[main]]
  name = "Methods"
  pageRef = "methods"
  weight = 10

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 20

[[main]]
  name = "Guides"
  pageRef = "guides"
  weight = 30

[[main]]
  name = "People"
  pageRef = "authors"
  weight = 40

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 50
