# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 5

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10
  
[[main]]
  name = "Guides"
  pageRef = "guides"
  weight = 20

[[main]]
  name = "Artifacts"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 40

[[main]]
  name = "Methods"
  pageRef = "methods"
  weight = 50

[[main]]
  name = "People"
  pageRef = "authors"
  weight = 60

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ianhussey/trustworthy.scientific.claims"
  weight = 70

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice.

[[footer]]
  name = "License"
  pageRef = "license"
  weight = 20

[[footer]]
  name = "Privacy Policy"
  pageRef = "privacy"
  weight = 30
